version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: gymtracker-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gym_tracker
    command: [ "postgres", "-c", "port=5433" ]
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gymtracker-api:
    build:
      context: ./backend/GymTracker 
      dockerfile: GymTracker/Dockerfile
    container_name: gymtracker-api
    environment:
      - JWT_KEY=your_jwt_secret_key
      - JWT_ISSUER=my_app
      - JWT_AUDIENCE=my_app_users
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5433;Database=gym_tracker;Username=postgres;Password=postgres
    ports:
      - "5000:80"
    depends_on:
      - postgres-db

volumes:
  postgres-data:
