services:
  gymtracker-postgres-db:
    image: postgres:latest
    container_name: gymtracker-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gym_tracker
    command: [ "postgres", "-c", "port=5433" ]
    ports:
      - "5433:5433"

  gymtracker-api:
    build:
      context: ./backend/GymTracker 
      dockerfile: GymTracker/Dockerfile
    container_name: gymtracker-api
    env_file:
      - ./backend/GymTracker/GymTracker/.env
    ports:
      - "5000:80"
    depends_on:
      - gymtracker-postgres-db

