services:
  gymtracker-postgres-db:
    image: postgres:latest
    container_name: gymtracker-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gym_tracker
    command: [ "postgres", "-c", "port=5433" ]
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5433"]
      interval: 5s
      retries: 5

  gymtracker-api:
    build:
      context: ./backend/GymTracker 
      dockerfile: GymTracker/Dockerfile
    container_name: gymtracker-api
    environment:
      - APPLY_MIGRATIONS=true
    env_file:
      - ./backend/GymTracker/GymTracker/.env
    ports:
      - "5000:5000"
    depends_on:
      gymtracker-postgres-db:
        condition: service_healthy
  
  gymtracker-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gymtracker-frontend
    depends_on:
      - gymtracker-api
    ports:
      - "4200:4200"

